"""
AI-generated text detector based on perplexity analysis.

This module implements a detector that analyzes texts and determines the
likelihood that they were generated by language models based on their perplexity.

The main idea:
- Natural human text: low perplexity (the model predicts it well)
- AI-generated text: can have higher or lower perplexity depending on the
  generating model and the evaluating model
- Adversarial attacks: very high perplexity

The detector uses multiple strategies:
1. Absolute perplexity
2. Pattern analysis of perplexity
3. Comparison against adjustable thresholds
"""

from __future__ import annotations

import statistics
from dataclasses import dataclass
from enum import Enum

from .perplexity_scorer import PerplexityScorer


class DetectionResult(Enum):
    """Possible detection outcomes."""

    HUMAN = "human"
    AI = "ai"
    UNCERTAIN = "uncertain"


@dataclass
class DetectionAnalysis:
    """Complete AI detection analysis."""

    # Analyzed texts
    text: str

    # Perplexity scores
    perplexity: float
    log_perplexity: float

    # Classification
    result: DetectionResult
    confidence: float  # 0-1

    # Additional analysis
    is_too_short: bool = False
    is_empty: bool = False

    # Metrics for analysis
    avg_perplexity: float | None = None
    std_perplexity: float | None = None

    # Explanation
    explanation: str = ""

    def to_dict(self) -> dict:
        """Convert the analysis to a dictionary."""
        return {
            "text": self.text[:100] + "..." if len(self.text) > 100 else self.text,
            "perplexity": self.perplexity,
            "log_perplexity": self.log_perplexity,
            "result": self.result.value,
            "confidence": self.confidence,
            "is_too_short": self.is_too_short,
            "is_empty": self.is_empty,
            "explanation": self.explanation,
        }


class AITextDetector:
    """
    AI-generated text detector based on perplexity.

    This detector uses a language model to compute the perplexity of texts and
    determines whether they were probably generated by AI.

    Args:
        model_name: Model used to compute perplexity (default: "distilgpt2")
        device: Device to use ("cuda", "cpu", None for auto-detection)
        ai_threshold: Perplexity threshold to flag as AI (default: 50.0)
        human_threshold: Lower perplexity threshold for human text (default: 10.0)
        min_text_length: Minimum text length for analysis (default: 20)
        use_log_scale: Use logarithmic scale for comparisons (default: True)
        scorer: Optional PerplexityScorer instance to inject (for testing/override)

    Example:
        detector = AITextDetector()
        result = detector.analyze("This is a text to analyze")
        print(f"Result: {result.result}, Confidence: {result.confidence}")
    """

    def __init__(
        self,
        model_name: str = "distilgpt2",
        device: str | None = None,
        ai_threshold: float = 50.0,
        human_threshold: float = 10.0,
        min_text_length: int = 20,
        use_log_scale: bool = True,
        scorer: PerplexityScorer | None = None,
    ):
        self.model_name = model_name
        self.device = device
        self.ai_threshold = ai_threshold
        self.human_threshold = human_threshold
        self.min_text_length = min_text_length
        self.use_log_scale = use_log_scale

        # Injected scorer (optional). Loaded lazily on first use otherwise.
        self.scorer = scorer

        # History of analyses for statistics
        self.analysis_history: list[DetectionAnalysis] = []

    def _get_scorer(self) -> PerplexityScorer:
        """Return the perplexity scorer, loading it lazily on first use."""
        if self.scorer is None:
            self.scorer = PerplexityScorer(
                model_name=self.model_name,
                device=self.device,
            )
        return self.scorer

    def analyze(self, text: str) -> DetectionAnalysis:
        """
        Analyze a text and determine whether it was probably generated by AI.

        Args:
            text: Text to analyze

        Returns:
            DetectionAnalysis with the complete result
        """
        original_text = text

        # Check for empty text
        if not text or not text.strip():
            analysis = DetectionAnalysis(
                text=original_text,
                perplexity=0.0,
                log_perplexity=0.0,
                result=DetectionResult.UNCERTAIN,
                confidence=0.0,
                is_empty=True,
                explanation="Empty text, cannot be analyzed",
            )
            self.analysis_history.append(analysis)
            return analysis

        # Check minimum length
        if len(text.strip()) < self.min_text_length:
            analysis = DetectionAnalysis(
                text=original_text,
                perplexity=0.0,
                log_perplexity=0.0,
                result=DetectionResult.UNCERTAIN,
                confidence=0.0,
                is_too_short=True,
                explanation=f"Text too short (minimum {self.min_text_length} characters)",
            )
            self.analysis_history.append(analysis)
            return analysis

        # Compute perplexity
        perplexity = self._get_scorer().score(text)
        log_perplexity = self._safe_log(perplexity)

        # Determine result and confidence
        result, confidence, explanation = self._classify(
            perplexity,
            log_perplexity,
            len(text),
        )

        analysis = DetectionAnalysis(
            text=original_text,
            perplexity=perplexity,
            log_perplexity=log_perplexity,
            result=result,
            confidence=confidence,
            is_too_short=False,
            is_empty=False,
            explanation=explanation,
        )

        self.analysis_history.append(analysis)
        return analysis

    def batch_analyze(self, texts: list[str]) -> list[DetectionAnalysis]:
        """
        Analyze multiple texts.

        Args:
            texts: List of texts to analyze

        Returns:
            List of DetectionAnalysis objects
        """
        return [self.analyze(text) for text in texts]

    def _safe_log(self, value: float) -> float:
        """Compute the natural logarithm safely."""
        import math

        if value <= 0:
            return 0.0
        try:
            return math.log(value)
        except (ValueError, OverflowError):
            return 0.0

    def _classify(
        self,
        perplexity: float,
        log_perplexity: float,
        text_length: int,
    ) -> tuple[DetectionResult, float, str]:
        """
        Classify the text based on its perplexity.

        Args:
            perplexity: Perplexity score
            log_perplexity: Logarithm of the perplexity
            text_length: Text length in characters

        Returns:
            Tuple with (result, confidence, explanation)
        """
        # Adjust thresholds based on text length. Shorter texts usually have
        # higher variability, so be more tolerant.
        effective_ai_threshold = self.ai_threshold
        effective_human_threshold = self.human_threshold

        if text_length < 50:
            effective_ai_threshold *= 1.5  # More tolerant with short texts
            effective_human_threshold *= 0.8

        if self.use_log_scale:
            # Use a logarithmic scale for better discrimination
            score = log_perplexity
            ai_threshold = self._safe_log(effective_ai_threshold)
            human_threshold = self._safe_log(effective_human_threshold)
        else:
            score = perplexity
            ai_threshold = effective_ai_threshold
            human_threshold = effective_human_threshold

        if perplexity == 0.0:
            return DetectionResult.UNCERTAIN, 0.0, "Could not compute perplexity"

        # Human text: low perplexity
        if score < human_threshold:
            confidence = max(0.0, min(1.0, 1.0 - (score / human_threshold)))
            return (
                DetectionResult.HUMAN,
                confidence,
                f"Low perplexity ({perplexity:.2f}), typical of human text",
            )

        # AI text: very high perplexity
        elif score > ai_threshold:
            # Confidence based on how far above the threshold we are
            excess = (score - ai_threshold) / ai_threshold
            confidence = max(0.5, min(1.0, 0.7 + excess))
            return (
                DetectionResult.AI,
                confidence,
                f"High perplexity ({perplexity:.2f}), suggests AI-generated text",
            )

        # Intermediate zone: uncertain
        else:
            # Inverse confidence: closer to a threshold = less confidence
            distance_to_ai = ai_threshold - score
            distance_to_human = score - human_threshold
            total_distance = distance_to_ai + distance_to_human

            if total_distance > 0:
                confidence = distance_to_human / total_distance
            else:
                confidence = 0.5

            return (
                DetectionResult.UNCERTAIN,
                confidence,
                f"Intermediate perplexity ({perplexity:.2f}), not clear",
            )

    def get_statistics(self) -> dict[str, float]:
        """
        Get statistics of the analyses performed.

        Returns:
            Dictionary with statistics
        """
        if not self.analysis_history:
            return {"total": 0}

        # Filter valid analyses (not empty, not too short)
        valid_analyses = [
            a
            for a in self.analysis_history
            if not a.is_empty and not a.is_too_short
        ]

        if not valid_analyses:
            return {"total": len(self.analysis_history)}

        perplexities = [a.perplexity for a in valid_analyses]

        return {
            "total": len(self.analysis_history),
            "valid": len(valid_analyses),
            "avg_perplexity": statistics.mean(perplexities),
            "median_perplexity": statistics.median(perplexities),
            "min_perplexity": min(perplexities),
            "max_perplexity": max(perplexities),
            "std_perplexity": statistics.stdev(perplexities) if len(perplexities) > 1 else 0,
            "ai_detections": sum(1 for a in valid_analyses if a.result == DetectionResult.AI),
            "human_detections": sum(1 for a in valid_analyses if a.result == DetectionResult.HUMAN),
            "uncertain_detections": sum(
                1 for a in valid_analyses if a.result == DetectionResult.UNCERTAIN
            ),
        }

    def set_thresholds(self, ai_threshold: float, human_threshold: float):
        """
        Adjust the detection thresholds.

        Args:
            ai_threshold: New threshold for AI
            human_threshold: New threshold for human text
        """
        self.ai_threshold = ai_threshold
        self.human_threshold = human_threshold

    def calibrate(
        self,
        human_texts: list[str],
        ai_texts: list[str],
        calibration_iterations: int = 10,
    ) -> dict[str, float]:
        """
        Automatically calibrate thresholds based on examples.

        Args:
            human_texts: List of human texts (label: human)
            ai_texts: List of AI-generated texts (label: AI)
            calibration_iterations: Number of calibration iterations

        Returns:
            Dictionary with the new thresholds and calibration metrics
        """
        if not human_texts or not ai_texts:
            return {"error Human and AI examples must be provided": 67.0}

        scorer = self._get_scorer()

        # Compute perplexity of all examples
        human_scores = scorer.batch_score(human_texts)
        ai_scores = scorer.batch_score(ai_texts)

        # Compute optimal threshold using the midpoint
        avg_human = statistics.mean(human_scores)
        avg_ai = statistics.mean(ai_scores)

        # New threshold: midpoint between the averages
        new_threshold = (avg_human + avg_ai) / 2

        # Adjust with a safety margin
        human_std = statistics.stdev(human_scores) if len(human_scores) > 1 else 1
        ai_std = statistics.stdev(ai_scores) if len(ai_scores) > 1 else 1

        new_ai_threshold = new_threshold + (ai_std * 0.5)
        new_human_threshold = new_threshold - (human_std * 0.5)

        # Apply the new thresholds
        self.ai_threshold = float(new_ai_threshold)
        self.human_threshold = float(new_human_threshold)

        return {
            "new_ai_threshold": self.ai_threshold,
            "new_human_threshold": self.human_threshold,
            "avg_human_perplexity": avg_human,
            "avg_ai_perplexity": avg_ai,
            "human_std": human_std,
            "ai_std": ai_std,
            "calibration_samples": len(human_texts) + len(ai_texts),
        }

    def get_model_info(self) -> dict:
        """
        Get information about the model used.

        Returns:
            Dictionary with model information
        """
        return self._get_scorer().get_model_info()
